set lines 200
col "IN" format a10
col "OUT" format a10
col "DEV" format a4
col "TIME_TAKEN" a10
select
START_TIME,
END_TIME,
--INPUT_BYTES/1024/1024/1024 "IN GB",
--OUTPUT_BYTES/1024/1024/1024 "OUT GB",
INPUT_BYTES_DISPLAY "IN",
OUTPUT_BYTES_DISPLAY "OUT",
SUBSTR(OUTPUT_DEVICE_TYPE,1,4)  "DEV",
STATUS,
INPUT_TYPE,
TIME_TAKEN_DISPLAY "TIME TAKEN"
from 
V$RMAN_BACKUP_JOB_DETAILS;
